spring:
  application:
    name: admin-server
  security: # 配置登录用户名和密码
    user:
      name: tang
      password: 123456
    boot:  # 不显示admin-server的监控信息
      admin:
        discovery:
          ignored-services: ${spring.application.name}
server:
  port: 9301
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://tang:123456@localhost:8004/eureka/
