server:
  port: 8701
spring:
  application:
    name: feign-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1.0 #设置Sleuth的抽样收集概率 默认0.1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://tang:123456@localhost:8004/eureka/
feign:
  hystrix:
    enabled: true #在Feign中开启Hystrix
logging:
  level:
    com.tang.cloud.service.UserService: debug
