server:
  port: 8801
spring:
  application:
    name: zuul-proxy
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://tang:123456@localhost:8004/eureka/
zuul:
  routes: #给服务配置路由
    user-service:
      path: /userService/**
    feign-service:
      path: /feignService/**
  ignored-services: user-service,feign-service #关闭默认路由配置
  prefix: /proxy #给网关路由添加前缀
  #Zuul在请求路由时，默认会过滤掉一些敏感的头信息，以下配置可以防止路由时的Cookie及Authorization的丢失：
  sensitive-headers: Cookie,Set-Cookie,Authorization #配置过滤敏感的请求头信息，设置为空就不会过滤
  #Zuul在请求路由时，不会设置最初的host头信息，以下配置可以解决：
  add-host-header: true #设置为true重定向是会添加host请求头
  retryable: true # 关闭重试机制
#  PreLogFilter:   #禁用过滤器
#    pre:
#      disable: true
management:
  endpoints:
    web:
      exposure:
        include: 'routes' #开启查看路由的端点：
ribbon: #全局配置
  ConnectTimeout: 1000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
hystrix:
  command: #用于控制HystrixCommand的行为
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000 #配置HystrixCommand执行的超时时间，执行超过该时间会进行服务降级处理
