server:
  port: 8401
spring:
  application:
    name: hystrix-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1.0 #设置Sleuth的抽样收集概率 默认0.1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://tang:123456@localhost:8004/eureka/
service-url:
  user-service: http://user-service
